# Generated by Django 3.1.12 on 2026-01-27 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_auto_20260127_1826"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creat"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="events.event",
                verbose_name="Esdeveniment",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminat"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="is_highlighted",
            field=models.BooleanField(default=False, verbose_name="Destacat"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(max_length=500, verbose_name="Missatge"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuari",
            ),
        ),
    ]
